version: '3'

services:

  selenide-tests:
    container_name: tests
    build: .
    volumes:
      - "./report:/home/gradle/src/report"
    command: bash -c "gradle test"
    #ports:
     # - "5432:5432"
    depends_on:
      - "selenoid"
    network_mode: service:selenoid

  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:latest-release
    volumes:
      - "$PWD/config:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: [
        "-conf", "/etc/selenoid/browsers.json",
        "-service-startup-timeout", "3m0s",
        "-session-attempt-timeout", "3m0s",
        "-session-delete-timeout", "3m0s",
        "-timeout", "5m0s"
    ]
    ports:
      - "4444:4444"