# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Selenide-Selenoid-Cucumber-Gradle-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download and cofigure Selenoid Configuration Manager (+ pull browsers)
      run: curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid configure --browsers "chrome" --last-versions 1 --config-dir config

    - name: Create Cucumber report folder
      run: mkdir report

    - name: Write permossions for report folder
      run: chmod 777 report

    - name: Start Selenoid
      run: docker-compose -f docker-compose-actions.yml up --build --abort-on-container-exit

    - name: Stop Selenoid
      run: docker-compose -f docker-compose-actions.yml down

    - name: Upload report as artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test_report
        path: ${{ github.workspace }}/report/cucumber-html-report.html