# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Selenide-Cucumber-Gradle-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Download Selenoid Configuration Manager
      run: curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid configure --browsers "chrome" --last-versions 1 --config-dir config
    - run: cat config/browsers.json

    - run: mkdir -p $PWD/opt/

    - name: Docker compose
      run: docker-compose up -d

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload report
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test_report
        path: ${{ github.workspace }}/target/cucumber-html-report.html