# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Selenide-Selenoid-Cucumber-Gradle-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    #- name: Download and cofigure Selenoid Configuration Manager (+ pull browsers)
    #  run: curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid configure --browsers "chrome" --last-versions 1 --config-dir config

    #- name: Check Containers
    #  run: docker ps -a

    #- name: Check Images
    #  run: docker images

    - name: Create Cucumber report folder
      run: mkdir report

    - name: Pull Chrome Image
      run: docker pull selenoid/vnc_chrome:87.0

    - name: Start Selenoid
      run: docker-compose -f docker-compose-linux.yml up --build --abort-on-container-exit

    - name: Echo Selenoid IP
      run: docker inspect --format '{{ .NetworkSettings.IPAddress }}' selenoid

    - name: Print Tests log
      run: docker logs tests

    - name: Print Selenoid log
      run: docker logs selenoid

    - name: Stop Selenoid
      run: docker-compose -f docker-compose-linux.yml down

    - name: Upload report as artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test_report
        path: ${{ github.workspace }}/report/cucumber-html-report.html